### ISSUE TITLE
outdated ‘write_inwf’ in WIEN2k 16.1

### ISSUE THREAD

**Issue by zanatkamel** [wien2wannier/wien2wannier#14]
Dear all,
I use wien2wannier from wien2k16.1, when I initialize the calculations for w2w in spin polarized one I get this error:

> init_w2w  -up 

> write_inwf:  error: unrecognized arguments: -up

**Comment by eassmann** [comment]
This is due to an outdated `write_inwf_lapw` which was included in WIEN2k 16.1 as originally published, see [this thread on the mailing list](http://www.mail-archive.com/wien@zeus.theochem.tuwien.ac.at/msg15140.html).

To fix the problem, download the [updated `SRC.tar.gz`](http://susi.theochem.tuwien.ac.at/reg_user/wien2k_download/files/SRC.tar.gz).

Note: For WIEN2k 16.1 as downloaded after 2016-12-15, there should be no problem.

Thanks for reporting.
